### ISSUE TITLE
useQueryState() -> useLocation() may be used only in the context of a <Router> component.   V3.1.2 with react-router-dom 6.15.0

### ISSUE THREAD

**Issue by Rliulinz** [xiel/use-location-state#558]
error-logging.ts:3 Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (history.ts:494:11)
    at useLocation (hooks.tsx:104:3)
    at useReactRouterQueryStringInterface (react-router-use-location-state.esm.js:33:20)
    at useQueryState2 (react-router-use-location-state.esm.js:54:85)

The component is wrapped in the router since the useLocation() from react-router-dom works fine in the same component. But when calling useQueryState() in the same component, it reports the error above.

**Comment by Rliulinz** [comment]
This is solved by upgrading react-router-dom to the latest 6.16.0 to be consistent with react-router.
